CREATE DATABASE luacoderdb;
USE luacoderdb;
ALTER DATABASE luacoderdb CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE TABLE files (
    id INT AUTO_INCREMENT PRIMARY KEY,
    filename VARCHAR(255) NOT NULL,
    user VARCHAR(255) NOT NULL,
    content TEXT NOT NULL
);
ALTER TABLE files ADD UNIQUE KEY(filename, user);
ALTER TABLE files 
ADD COLUMN date_modified TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;